version: '3.8'

services:
  # DB Postgres
  # Refer: https://geshan.com.np/blog/2021/12/docker-postgres/
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      #- ./docker/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  db:
    driver: local